### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by porrasm** [alhopasi/ruokaa#1]
8.4 klo 20

### Sovellus

Sovellus on netissä toimiva reseptien jakamiseen tarkoitettu sivusto. Sovelluksessa käyttäjillä on mahdollisuus luoda ja selata reseptejä.

### Yleispalaute

Dokumentaatio näyttää olevan kunnossa. Käyttötapauksista on toteutettu kaikki toiminnot paitsi yksi (kommentointi ja äänestys). Nämä user storyt voisi vielä pilkkoa pienemmiksi; esimerkiksi storyssa 'Kirjautuneena haluan pystyä luomaan ruokia, muuttamaan niiden tietoja sekä poistamaan niitä.' on käytännössä kolme pientä yksittäistä storya. 

Sovellus näyttää hyvältä ja tyylit on otettu käyttöön. Ulkoasu on selkeä ja mainitut toiminnot ovat helposti toteutettavissa ja löydettävissä. Yksi muutosehdotus olisi, että 'rekisteröidy' ja 'kirjaudu' napit käyttäisivät samanlaista tyylittelyä. Rekisteröidy nappi näyttää ehkä hieman tylsältä muiden hienompien tyylien joukossa. 'Rekisteröidy' napissa myös lukee 'lisää' joka on epäselvä kuvaus toiminnolle.

Repositorion commiteissa kannattaa käyttää yhtä kieltä. Nyt osa commiteista on englanniksi ja osa suomeksi. Niitä kirjoittaessa kannattaa myös käyttää aina samanlaista 'syntaksia'. Tämä menee kuitenkin hieman jo pilkunviilauksen puolelle.

### Ongelmia ja bugeja

Käyttäjän tietojen muokkaus onnistuu ongelmitta, mutta kun yritän muuttaa reseptin tietoja tulee vastaan ikävä Internal Server Error. Jos yrittää lisätä ruoan pelkillä välilyöntiarvoilla tulee taas Internal Server Error. Napit, jotka käyttävät pop up confirm ikkunoita, luovat consoleen virheen: [Violation] 'click' handler took x ms. En osaa sanoa onko tämä ongelma tai miten tämä korjataan tai että onko tälle edes tarvetta korjata.

### Koodi

Koodi on laadukasta ja sen ymmärtämisessä ei ole ongelmaa. Metodit ja muuttujat on nimetty järkevästi ja ne kuvaavat sen toimintoja ja käyttötarkoitusta. Kuitenkin muutamia ongelmia on. Database modelissa käyttäjän tiedot on rajattu 144 merkkiin, mutta forms ei validoi sen pituutta (ainoastaan aliraja validoidaan). Jos käyttäjänimi on yli 144 merkkiä pitkä tulee Internal Server Error. Validointi on muutenkin hieman puuttellista, sillä esimerkiksi pelkkä whitespace ja/tai erikoismerkit hyväksytään kaikissa formseissa.

### Viimeiset sanat

Mielestäni sovellus on oikein hyvä ja aihevalinta on hyvä kurssin laajuudelle. Sovellus on hyvällä mallilla ja vastaa dokumentaatiota. Suuria puutteita ei ole, mutta sovelluksessa on muutama isompi bugi (internal server errorit).

**Comment by porrasm** [comment]
Yksi asia unohtui mainita vielä. Rekisteröintivaiheessa olisi hyvä jos uusi käyttäjä kirjattaisiin samalla sisään. Myöskin edellämainittu click handler violation ei johdu sovelluksesta vaan Chromesta.

**Comment by alhopasi** [comment]
Kiitos palautteesta, korjasin useimmat asiat tuosta.
