### ISSUE TITLE
Koodikatselmointi2

### ISSUE THREAD

**Issue by Roeoeri** [alhopasi/ruokaa#2]
# Koodikatselmointi 2 <h1>

Ohjelma ladattu 29.4 klo 21

## Huomioita <h2>

Demosin sovellusta pääosin Herokussa, sillä siellä tietokannassa oli jo valmiiksi dataa jota testata. Kaiken kaikkiaan olet tehnyt hyvää työtä. Käyttötapaukset onnistuvat aivan kuten dokumentissa on kuvattu, enkä ainakaan itse saanut sovellusta hajalla (yrityksestä huolimatta). Sovellus oli mielestäni myös helppokäyttöinen ja helposti omaksuttava. 

Sovelluksen koodikin on samanlaista laadukasta jälkeä. Koodi on helppolukuista, sillä muuttujat yms. ovat nimetty kuvaavasti ja koodi etenee loogisesti. Myöskin muotoilultaan koodi on nättiä, eikä siinä ole esimerkiksi  ylimääräisiä tyhjiä rivejä.

Sovelluksessa ei oikein puutteita ollut, mutta olen yrittänyt kasata alle pieniä huomioita ja kehitysideoita.

## Pieniä huomioita <h2>

Kirjauduttaessa käyttäjätunnuksella jota ei ole olemassa, sovellus ei näytä virheilmoitusta puuttuvaan käyttäjään liittyen, vaan palauttaa kirjautumislomakkeen ilman virheviestejä. Virheilmoitus parantaisi sovelluksen käytettävyyttä. 

A-checkerin mukaan sivullasi ei ole määritelty kieltä. Ongelma on helppo korjata muuttamalla layout.html ensinmäinen html tagi muotoon ` <html lang ="fi">` . Tämän pitäisi ainakin A-checkerin mukaan parantaa saavutettavuutta.

## Kehitysideoita <h2>

Kun käyttäjä yrittää hakea/tykätä ruuasta, jota ei ole olemassa (esimerkiksi menemällä osoitteeseen https://ruokaa-app.herokuapp.com/foods/123213213123123123123123123/), sovellus antaa vain Internal server error- virhesivun. Tällaisiin tilanteisiin olisi ehkä hyvä tehdä oma html-template, jossa kerrotaan virheen tapahtuneen ja ohjataan käyttäjä takaisin toimivalle sivustolle.

## Pilkunviilausta/muuta mieleen tullutta<h2>

*Seuraavat asiat eivät liity enää varsinaisesti koodikatselmointiin, mutta saattavat olla kenties hyödyllisiä.*

Tällä hetkellä sovelluksesi poistaa tietoja kun käyttäjä tekee HTTP Get-pyynnön osoitteeseen https://ruokaa-app.herokuapp.com/foods/delete/<id>. Vaikka pyynnön tekijä validoidaankin palvelimella, on yleinen käytäntö, että Get-pyynnöllä haetaan vain dataa, eikä se muuta palvelimen tilaa. Aiheesta löytyy keskustelua esimerkiksi [Täältä](https://stackoverflow.com/questions/786070/why-should-you-delete-using-an-http-post-or-delete-rather-than-get). Olisi ehkä siis parempi muuttaa poistaminen vaikka Post-pyynnöksi (tai kaikkien taiteen sääntöjen mukaisesti Delete-pyynnöksi, mutta se lienee Html:sta johtuen hankalaa). 

En tiedä, johtuuko tapaus vain omasta koneestani, mutta seuratessani sovelluksen asennusohjetta, sovellusta ei saanut avattua komennolla `python3 run.py` ennen virtuaaliympäristön luomista. Kokeilin samaa myös omassa projektissani, eikä projektia saanut auki ennen komennon  `source venv/bin/activate` suorittamista. Mikäli tapaus ei ole vain omasta koneestani kiinni, asennusohjetta voisi ehkä päivittää ohjeella virtuaaliympäristön luomisesta, eli lisätä komennot:

`python3 -m venv venv`
`source venv/bin/activate`

**Comment by alhopasi** [comment]
Jes. Kiitos kommenteista. Olitpa tehnyt perusteellista työtä tässä katselmoinnissa!
En lähde tuota HTTP Delete pyyntöä tutkimaan nyt, kurssi on sen verran lähellä loppua etten käytä siihen aikaa. Korjasin nuo muut jutut. Mulla oli jo aiemmin virheilmoitus kirjautumisen yhteydessä, mutta olin vahingossa poistanut sen refaktoroinnin yhteydessä. Ja tuo foods/22222... johtui herokun postgresql:n tapauksesta jos kutsuu yli kokonaisluvun arvoista ruokaa, kun tietokannassa id on kokonaislukuna. Korjasin tuonkin koodiin.
